name: CI - Java 21

on:
  push:
    branches: [ 'main', 'master', 'develop' ]
  pull_request:
    branches: [ 'main', 'master', 'develop' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew

    - name: Build
      run: |
        ./gradlew build --warning-mode all

    - name: Run unit tests
      run: |
        ./gradlew test

    - name: Run assemble debug (optional)
      run: |
        ./gradlew assembleDebug
